---
title: "ID05"
author: "Grupo 05"
date: "16/01/2020"
output:
  html_document: default
  pdf_document: default
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```

```{r read dados cancro}
dadoscancro<- read.csv(file = "data/CancerMortalityEU.csv")
names(dadoscancro)
```


```{r dados pop}
dadospopulacao <- read.csv( file = "data/PopulationEU.csv")
names(dadospopulacao)
```

```{r packages}
install.packages("data.table")
install.packages("rmarkdown")
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("here")
install.packages(c("tidyr", "devtools"))
library(data.table)
library(rmarkdown)
library(tidyr)
library(devtools)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(here)
```

```{r organizar dataframe da população}
novopop<-dadospopulacao[,-c(3,5)]
names(novopop)

POP<-gather(novopop,"Year","pop",4:22)
POP$Year<-sub(".", "", POP$Year)  #Tirar o primeiro caracter (X) dos anos
POP <- na.omit(POP)
```


```{r all idades pop}
totoid<- aggregate(POP$pop, by=list(POP$Year, POP$Country, POP$Sex), FUN=sum)
#Dataframe das mortes relativas ao cancro por Ano, País e Sexo
setnames(totoid, old = c("Group.1","Group.2","Group.3","x"), new = c("Year", "Country", "Sex","pop"))
names(totoid)
names(POP)
totoid<- totoid[-c(1063:1593),]



ageGroup<-rep("All", times = 1062)
totoid<-cbind(totoid,ageGroup)

POP<- rbind(POP, totoid)

```



```{r organizar dataframe dos cancros}

#Cancros
names(dadoscancro)
novocancro<-dadoscancro[,-c(2,4,6)]
names(novocancro)
View(novocancro)
CANCRO<-gather(novocancro,"Year","cancer",4:17)
Sex<- rep(c("Females", "Males"), times = c(63504,63504))
CANCRO<-cbind(CANCRO,Sex)

CANCRO$Year<-sub("Females", "", CANCRO$Year) #Tirar a palavra Females dos anos
CANCRO$Year<-sub("Males", "", CANCRO$Year) #Tirar a palavra Males dos anos
CANCRO$Year<-sub(".", "", CANCRO$Year) #Tirar o underscore dos anos

CANCRO <- na.omit(CANCRO) #NO ENVIRONMENT NAO APARECE AS OBSERVACOES CERTAS


CANCRO<- CANCRO[CANCRO$CancerSite=="Bladder",]
View(CANCRO)

```


```{r all idades cancro}
mortes<- aggregate(CANCRO$cancer, by=list(CANCRO$Year, CANCRO$Country, CANCRO$Sex, CANCRO$CancerSite), FUN=sum)
#Dataframe das mortes relativas ao cancro por Ano, País e Sexo
setnames(mortes, old = c("Group.1","Group.2","Group.3","Group.4","x"), new = c("Year", "Country", "Sex","CancerSite","cancer"))
names(mortes)
names(CANCRO)


ageGroup<-rep("All", times = 374)
mortes<-cbind(mortes,ageGroup)

CANCRO<- rbind(CANCRO, mortes)

```



```{r criar a dataset}

total<-merge(POP,CANCRO, by=c("Country", "Sex", "Year", "ageGroup"))
#Junção do CANCRO e POP para termos as duas dataframes cruzadas


```


```{r mrate2}

mRate <- 100000*(total$cancer/total$pop)
mRate<-round(mRate,3)

TabelaFinal<- cbind(total,mRate)
TabelaFinal
View(TabelaFinal)
```



```{r questão 1}

Paises_mulheres<- TabelaFinal[TabelaFinal$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal") & TabelaFinal$Sex=="Females" & TabelaFinal$ageGroup=="All",]
View(Paises_mulheres)

ggplot(Paises_mulheres, aes(x=Paises_mulheres$Year, y=Paises_mulheres$mRate, group=Paises_mulheres$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_mulheres$Country) +
  labs(title = "Ratio de mortes feminino nos países selecionados", x= "Ano", y= "Ratio de mortes", color = "Paises")



Paises_homens<- TabelaFinal[TabelaFinal$Country %in% c("Belgium", "Finland", "Italy", "Netherlands", "Portugal") & TabelaFinal$Sex=="Males" & TabelaFinal$ageGroup=="All",]


ggplot(Paises_homens, aes(x=Paises_homens$Year, y=Paises_homens$mRate, group=Paises_homens$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_homens$Country) +
  labs(title = "Ratio de mortes masculino nos países selecionados", x= "Ano", y= "Ratio de mortes", color = "Paises")

```

```{r questão 1 UE}
Paisestodos_mulheres<-TabelaFinal[TabelaFinal$Sex=="Females" & TabelaFinal$ageGroup=="All",-8]
sPOPPaisestodos_mulheres<- aggregate(Paisestodos_mulheres$pop, by=list(Paisestodos_mulheres$Year), FUN=sum)

sCANCERPaisestodos_mulheres<- aggregate(Paisestodos_mulheres$cancer, by=list(Paisestodos_mulheres$Year), FUN=sum)

uniaoeuropeia<-cbind(sPOPPaisestodos_mulheres,sCANCERPaisestodos_mulheres)
uniaoeuropeia<-uniaoeuropeia[,-3]
setnames(uniaoeuropeia,old=c("Group.1","x","x.1"), new=c("Year","pop","cancer"))
mRate <- 100000*(uniaoeuropeia$cancer/uniaoeuropeia$pop)
mRate<-round(mRate,3)
uniaoeuropeiafinalmulheres<- cbind(uniaoeuropeia,mRate)
View(uniaoeuropeiafinal)
Country<-rep("European Union",7)
Sex<-rep("Females",7)
CancerSite<-rep("Bladder",7)
ageGroup<-rep("All",7)
uniaoeuropeiafinalmulheres<-cbind(Country,uniaoeuropeiafinalmulheres,Sex,CancerSite,ageGroup)
View(uniaoeuropeiafinalmulheres)
Paises_mulheres<-rbind(uniaoeuropeiafinalmulheres,Paises_mulheres)


Paisestodos_homens<-TabelaFinal[TabelaFinal$Sex=="Males" & TabelaFinal$ageGroup=="All",-8]
sPOPPaisestodos_homens<- aggregate(Paisestodos_homens$pop, by=list(Paisestodos_homens$Year), FUN=sum)

sCANCERPaisestodos_homens<- aggregate(Paisestodos_homens$cancer, by=list(Paisestodos_homens$Year), FUN=sum)

uniaoeuropeia<-cbind(sPOPPaisestodos_homens,sCANCERPaisestodos_homens)
uniaoeuropeia<-uniaoeuropeia[,-3]
setnames(uniaoeuropeia,old=c("Group.1","x","x.1"), new=c("Year","pop","cancer"))
mRate <- 100000*(uniaoeuropeia$cancer/uniaoeuropeia$pop)
mRate<-round(mRate,3)
uniaoeuropeiafinalhomens<- cbind(uniaoeuropeia,mRate)
View(uniaoeuropeiafinalhomens)

Country<-rep("União Europeia",7)
Sex<-rep("Males",7)
CancerSite<-rep("Bladder",7)
ageGroup<-rep("All",7)
uniaoeuropeiafinalhomens<-cbind(Country,uniaoeuropeiafinalhomens,Sex,CancerSite,ageGroup)
View(uniaoeuropeiafinalhomens)
Paises_homens<-rbind(uniaoeuropeiafinalhomens,Paises_homens)



ggplot(Paises_mulheres, aes(x=Paises_mulheres$Year, y=Paises_mulheres$mRate, group=Paises_mulheres$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_mulheres$Country)+
  labs(title = "Ratio de mortes feminino nos países selecionados e na UE", x= "Ano", y= "Ratio de mortes", color = "Paises")

ggplot(Paises_homens, aes(x=Paises_homens$Year, y=Paises_homens$mRate, group=Paises_homens$Country)) +
  geom_line()+
  geom_point()+
  aes(colour = Paises_homens$Country)+
  labs(title = "Ratio de mortes masculino nos países selecionados e na UE", x= "Ano", y= "Ratio de mortes", color = "Paises")
 


```

